Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.17/x64/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.8.17/x64/lib/python3.8/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.8.17/x64/lib/python3.8/site-packages/jupyter_core/utils/__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
  File "/opt/hostedtoolcache/Python/3.8.17/x64/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.8.17/x64/lib/python3.8/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.8.17/x64/lib/python3.8/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.8.17/x64/lib/python3.8/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
couette = pd.read_excel('couette.xls',
                   sheet_name='Flow sweep - 1',
                   header=1) # sheet name is case sensitive, excel file name is not

couette
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
File [0;32m/opt/hostedtoolcache/Python/3.8.17/x64/lib/python3.8/site-packages/pandas/compat/_optional.py:142[0m, in [0;36mimport_optional_dependency[0;34m(name, extra, errors, min_version)[0m
[1;32m    141[0m [38;5;28;01mtry[39;00m:
[0;32m--> 142[0m     module [38;5;241m=[39m [43mimportlib[49m[38;5;241;43m.[39;49m[43mimport_module[49m[43m([49m[43mname[49m[43m)[49m
[1;32m    143[0m [38;5;28;01mexcept[39;00m [38;5;167;01mImportError[39;00m:

File [0;32m/opt/hostedtoolcache/Python/3.8.17/x64/lib/python3.8/importlib/__init__.py:127[0m, in [0;36mimport_module[0;34m(name, package)[0m
[1;32m    126[0m         level [38;5;241m+[39m[38;5;241m=[39m [38;5;241m1[39m
[0;32m--> 127[0m [38;5;28;01mreturn[39;00m [43m_bootstrap[49m[38;5;241;43m.[39;49m[43m_gcd_import[49m[43m([49m[43mname[49m[43m[[49m[43mlevel[49m[43m:[49m[43m][49m[43m,[49m[43m [49m[43mpackage[49m[43m,[49m[43m [49m[43mlevel[49m[43m)[49m

File [0;32m<frozen importlib._bootstrap>:1014[0m, in [0;36m_gcd_import[0;34m(name, package, level)[0m

File [0;32m<frozen importlib._bootstrap>:991[0m, in [0;36m_find_and_load[0;34m(name, import_)[0m

File [0;32m<frozen importlib._bootstrap>:973[0m, in [0;36m_find_and_load_unlocked[0;34m(name, import_)[0m

[0;31mModuleNotFoundError[0m: No module named 'xlrd'

During handling of the above exception, another exception occurred:

[0;31mImportError[0m                               Traceback (most recent call last)
Cell [0;32mIn[7], line 1[0m
[0;32m----> 1[0m couette [38;5;241m=[39m [43mpd[49m[38;5;241;43m.[39;49m[43mread_excel[49m[43m([49m[38;5;124;43m'[39;49m[38;5;124;43mcouette.xls[39;49m[38;5;124;43m'[39;49m[43m,[49m
[1;32m      2[0m [43m                   [49m[43msheet_name[49m[38;5;241;43m=[39;49m[38;5;124;43m'[39;49m[38;5;124;43mFlow sweep - 1[39;49m[38;5;124;43m'[39;49m[43m,[49m
[1;32m      3[0m [43m                   [49m[43mheader[49m[38;5;241;43m=[39;49m[38;5;241;43m1[39;49m[43m)[49m [38;5;66;03m# sheet name is case sensitive, excel file name is not[39;00m
[1;32m      5[0m couette

File [0;32m/opt/hostedtoolcache/Python/3.8.17/x64/lib/python3.8/site-packages/pandas/io/excel/_base.py:478[0m, in [0;36mread_excel[0;34m(io, sheet_name, header, names, index_col, usecols, dtype, engine, converters, true_values, false_values, skiprows, nrows, na_values, keep_default_na, na_filter, verbose, parse_dates, date_parser, date_format, thousands, decimal, comment, skipfooter, storage_options, dtype_backend)[0m
[1;32m    476[0m [38;5;28;01mif[39;00m [38;5;129;01mnot[39;00m [38;5;28misinstance[39m(io, ExcelFile):
[1;32m    477[0m     should_close [38;5;241m=[39m [38;5;28;01mTrue[39;00m
[0;32m--> 478[0m     io [38;5;241m=[39m [43mExcelFile[49m[43m([49m[43mio[49m[43m,[49m[43m [49m[43mstorage_options[49m[38;5;241;43m=[39;49m[43mstorage_options[49m[43m,[49m[43m [49m[43mengine[49m[38;5;241;43m=[39;49m[43mengine[49m[43m)[49m
[1;32m    479[0m [38;5;28;01melif[39;00m engine [38;5;129;01mand[39;00m engine [38;5;241m!=[39m io[38;5;241m.[39mengine:
[1;32m    480[0m     [38;5;28;01mraise[39;00m [38;5;167;01mValueError[39;00m(
[1;32m    481[0m         [38;5;124m"[39m[38;5;124mEngine should not be specified when passing [39m[38;5;124m"[39m
[1;32m    482[0m         [38;5;124m"[39m[38;5;124man ExcelFile - ExcelFile already has the engine set[39m[38;5;124m"[39m
[1;32m    483[0m     )

File [0;32m/opt/hostedtoolcache/Python/3.8.17/x64/lib/python3.8/site-packages/pandas/io/excel/_base.py:1513[0m, in [0;36mExcelFile.__init__[0;34m(self, path_or_buffer, engine, storage_options)[0m
[1;32m   1510[0m [38;5;28mself[39m[38;5;241m.[39mengine [38;5;241m=[39m engine
[1;32m   1511[0m [38;5;28mself[39m[38;5;241m.[39mstorage_options [38;5;241m=[39m storage_options
[0;32m-> 1513[0m [38;5;28mself[39m[38;5;241m.[39m_reader [38;5;241m=[39m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_engines[49m[43m[[49m[43mengine[49m[43m][49m[43m([49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_io[49m[43m,[49m[43m [49m[43mstorage_options[49m[38;5;241;43m=[39;49m[43mstorage_options[49m[43m)[49m

File [0;32m/opt/hostedtoolcache/Python/3.8.17/x64/lib/python3.8/site-packages/pandas/io/excel/_xlrd.py:34[0m, in [0;36mXlrdReader.__init__[0;34m(self, filepath_or_buffer, storage_options)[0m
[1;32m     24[0m [38;5;250m[39m[38;5;124;03m"""[39;00m
[1;32m     25[0m [38;5;124;03mReader using xlrd engine.[39;00m
[1;32m     26[0m 
[0;32m   (...)[0m
[1;32m     31[0m [38;5;124;03m{storage_options}[39;00m
[1;32m     32[0m [38;5;124;03m"""[39;00m
[1;32m     33[0m err_msg [38;5;241m=[39m [38;5;124m"[39m[38;5;124mInstall xlrd >= 2.0.1 for xls Excel support[39m[38;5;124m"[39m
[0;32m---> 34[0m [43mimport_optional_dependency[49m[43m([49m[38;5;124;43m"[39;49m[38;5;124;43mxlrd[39;49m[38;5;124;43m"[39;49m[43m,[49m[43m [49m[43mextra[49m[38;5;241;43m=[39;49m[43merr_msg[49m[43m)[49m
[1;32m     35[0m [38;5;28msuper[39m()[38;5;241m.[39m[38;5;21m__init__[39m(filepath_or_buffer, storage_options[38;5;241m=[39mstorage_options)

File [0;32m/opt/hostedtoolcache/Python/3.8.17/x64/lib/python3.8/site-packages/pandas/compat/_optional.py:145[0m, in [0;36mimport_optional_dependency[0;34m(name, extra, errors, min_version)[0m
[1;32m    143[0m [38;5;28;01mexcept[39;00m [38;5;167;01mImportError[39;00m:
[1;32m    144[0m     [38;5;28;01mif[39;00m errors [38;5;241m==[39m [38;5;124m"[39m[38;5;124mraise[39m[38;5;124m"[39m:
[0;32m--> 145[0m         [38;5;28;01mraise[39;00m [38;5;167;01mImportError[39;00m(msg)
[1;32m    146[0m     [38;5;28;01mreturn[39;00m [38;5;28;01mNone[39;00m
[1;32m    148[0m [38;5;66;03m# Handle submodules: if we have submodule, grab parent module from sys.modules[39;00m

[0;31mImportError[0m: Missing optional dependency 'xlrd'. Install xlrd >= 2.0.1 for xls Excel support Use pip or conda to install xlrd.

