Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.17/x64/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.8.17/x64/lib/python3.8/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.8.17/x64/lib/python3.8/site-packages/jupyter_core/utils/__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
  File "/opt/hostedtoolcache/Python/3.8.17/x64/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.8.17/x64/lib/python3.8/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.8.17/x64/lib/python3.8/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.8.17/x64/lib/python3.8/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import numpy as np
import json

import matplotlib.pyplot as plt

with open('../06-intermediate-sklearn/data.json') as f:
    data = json.load(f)

X = np.array([data['distance']]).T
y = data['energy']

from sklearn.neural_network import MLPRegressor

model = MLPRegressor(hidden_layer_sizes=(3,), activation='tanh', solver='lbfgs')
model.fit(X, y)

dfit = np.linspace(1.5, 7)

plt.plot(data['distance'], data['energy'], 'bo',
         dfit, model.predict(dfit[:, None]))

plt.xlabel('distance')
plt.ylabel('energy');
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [0;32mIn[1], line 12[0m
[1;32m      9[0m X [38;5;241m=[39m np[38;5;241m.[39marray([data[[38;5;124m'[39m[38;5;124mdistance[39m[38;5;124m'[39m]])[38;5;241m.[39mT
[1;32m     10[0m y [38;5;241m=[39m data[[38;5;124m'[39m[38;5;124menergy[39m[38;5;124m'[39m]
[0;32m---> 12[0m [38;5;28;01mfrom[39;00m [38;5;21;01msklearn[39;00m[38;5;21;01m.[39;00m[38;5;21;01mneural_network[39;00m [38;5;28;01mimport[39;00m MLPRegressor
[1;32m     14[0m model [38;5;241m=[39m MLPRegressor(hidden_layer_sizes[38;5;241m=[39m([38;5;241m3[39m,), activation[38;5;241m=[39m[38;5;124m'[39m[38;5;124mtanh[39m[38;5;124m'[39m, solver[38;5;241m=[39m[38;5;124m'[39m[38;5;124mlbfgs[39m[38;5;124m'[39m)
[1;32m     15[0m model[38;5;241m.[39mfit(X, y)

[0;31mModuleNotFoundError[0m: No module named 'sklearn'

